name: Update Routing Policy Action

on:
  workflow_dispatch:

jobs:
  update-routing-policy-action:
    runs-on: [analysts-demo]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Routing Policy Action
        run: |
          content=$(cat ${{ github.workspace }}/analysts-studio-petstore/Policies/routing/routing.json | jq)
          update_status=$(curl -o /dev/null -s -w "%{http_code}" --location --request PUT "${{ vars.baseURL }}/policyActions/4ac5f262-0776-480e-b94d-1887c324840c" -H "Authorization: ${{ secrets.basicAuth }}" -H "Content-Type: application/json" -d "{\"policyAction\": $content}")
          
          if [ "${update_status}" == "200" ]; then
            echo "Routing policy action updated successfully."
          else
            echo "Unable to update routing policy action."
          fi