name: Update Transport Policy Action

on:
  workflow_dispatch:

jobs:
  update-transport-policy-action:
    runs-on: [analysts-demo]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update Transport Policy Action
        run: |
          content=$(cat ${{ github.workspace }}/analysts-studio-petstore/Policies/transport/protocol.json | jq)
          update_status=$(curl -o /dev/null -s -w "%{http_code}" --location --request PUT "${{ vars.baseURL }}/policyActions/83e59dc2-9319-40ad-84ab-62ff893984e4" -H "Authorization: ${{ secrets.basicAuth }}" -H "Content-Type: application/json" -d '{"policyAction":$content}')
          
          if [ "${update_status}" == "200" ]; then
            echo "Transport policy action updated successfully."
          else
            echo "Unable to update Transport policy action."
          fi


